table dim_date
	lineageTag: 539f96a0-96fa-4f6e-a590-f275b32e385f

	column order_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a241a5be-a074-421d-8677-d80ca2462b92
		summarizeBy: none
		sourceColumn: order_date

		variation Variation
			isDefault
			relationship: 3ed0e39a-5eed-4a97-bd19-ef038a3f3f9b
			defaultHierarchy: LocalDateTable_3b820515-792d-4ace-a161-9ef9c2d3b9cd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column order_date_id
		dataType: int64
		formatString: 0
		lineageTag: 7a7de4c3-c93e-4cb4-b20b-4047e60e4ea0
		summarizeBy: none
		sourceColumn: order_date_id

		annotation SummarizationSetBy = Automatic

	column day_no
		dataType: int64
		formatString: 0
		lineageTag: 2f722029-085b-4874-b65c-49e1c17bf97a
		summarizeBy: sum
		sourceColumn: day_no

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 047f8b9a-879a-4ca7-bc2b-f4ae6f8d2449
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column month_no
		dataType: int64
		formatString: 0
		lineageTag: 63125776-26ce-483d-b77e-7e2a2bef17fe
		summarizeBy: sum
		sourceColumn: month_no

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 329f16a2-c62a-479d-be62-c60f4478337f
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column quarter_no
		dataType: int64
		formatString: 0
		lineageTag: 05d6dc97-95c8-41f9-ab1c-3d39aac218a8
		summarizeBy: sum
		sourceColumn: quarter_no

		annotation SummarizationSetBy = Automatic

	column quarter_name
		dataType: string
		lineageTag: 9491a377-b25b-43e2-97b5-edcb6073a471
		summarizeBy: none
		sourceColumn: quarter_name

		annotation SummarizationSetBy = Automatic

	column year_no
		dataType: int64
		formatString: 0
		lineageTag: da4a6074-d473-483e-9abe-82d7403aa658
		summarizeBy: sum
		sourceColumn: year_no

		annotation SummarizationSetBy = Automatic

	column year_month_id
		dataType: int64
		formatString: 0
		lineageTag: 8f3bc897-315f-42b2-99a9-b5377a89ece2
		summarizeBy: sum
		sourceColumn: year_month_id

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Projects\cafe-retail-data-generator\dim_date.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_date", type date}, {"order_date_id", Int64.Type}, {"day_no", Int64.Type}, {"day_name", type text}, {"month_no", Int64.Type}, {"month_name", type text}, {"quarter_no", Int64.Type}, {"quarter_name", type text}, {"year_no", Int64.Type}, {"year_month_id", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

