table dim_outlet
	lineageTag: f5d0b4ba-3021-4396-aa41-92194b800e0b

	column outlet_id
		dataType: int64
		formatString: 0
		lineageTag: 3eb9e575-da80-4605-a08f-187bd2e71f22
		summarizeBy: none
		sourceColumn: outlet_id

		annotation SummarizationSetBy = Automatic

	column outlet_location
		dataType: string
		lineageTag: 7cc5d01b-0343-4ab3-b8b5-d5ab2672121f
		summarizeBy: none
		sourceColumn: outlet_location

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: c8c685e3-4acd-4cca-a311-0bbdc9a9a668
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: b6aea9a5-0a9f-4c78-91c7-4ae0f9574bff
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	partition dim_outlet = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Projects\cafe-retail-data-generator\dim_outlet.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"outlet_id", Int64.Type}, {"outlet_location", type text}, {"region", type text}, {"state", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

