table dim_product
	lineageTag: 7367651a-5522-4870-a8a5-2fc23e9600fe

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: d5da16b9-2979-4eec-b0e4-321f1bf18cf2
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: 0f3d3e67-4dd2-46e0-9868-c975147a2be0
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column price
		dataType: int64
		formatString: 0
		lineageTag: c07d1fa2-3b89-4f34-b43c-a44a4cca6e73
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

	partition dim_product = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Projects\cafe-retail-data-generator\dim_product.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", Int64.Type}, {"product_name", type text}, {"price", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

