table fact_budget
	lineageTag: 8b50799c-1ab5-416f-bb50-b8722b3bf82d

	column outlet_id
		dataType: int64
		formatString: 0
		lineageTag: c4921b3a-740f-430d-ae9a-ba761916c625
		summarizeBy: none
		sourceColumn: outlet_id

		annotation SummarizationSetBy = Automatic

	column year_month_id
		dataType: int64
		formatString: 0
		lineageTag: aea004ad-3c29-461c-aa2a-33b81112f127
		summarizeBy: sum
		sourceColumn: year_month_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 704c77f7-2f01-4a8c-b32b-c2edbd468c15
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column cups_sold_budget
		dataType: int64
		formatString: 0
		lineageTag: 9d163f30-1f61-4061-9df8-7cc065d7a8d2
		summarizeBy: sum
		sourceColumn: cups_sold_budget

		annotation SummarizationSetBy = Automatic

	column gross_sales_budget
		dataType: int64
		formatString: 0
		lineageTag: 373405b1-00bc-45a1-ab70-f833c40fab03
		summarizeBy: sum
		sourceColumn: gross_sales_budget

		annotation SummarizationSetBy = Automatic

	column discount_budget
		dataType: int64
		formatString: 0
		lineageTag: 1611359b-5e32-47ef-b38f-0595c8770386
		summarizeBy: sum
		sourceColumn: discount_budget

		annotation SummarizationSetBy = Automatic

	column net_sales_budget
		dataType: int64
		formatString: 0
		lineageTag: 0506df71-052d-48f3-b725-09d4add8dad5
		summarizeBy: sum
		sourceColumn: net_sales_budget

		annotation SummarizationSetBy = Automatic

	column cost_budget
		dataType: int64
		formatString: 0
		lineageTag: 6355bdd3-d6e0-4c2d-bfd4-19c0a4ce347b
		summarizeBy: sum
		sourceColumn: cost_budget

		annotation SummarizationSetBy = Automatic

	column gross_profit_budget
		dataType: int64
		formatString: 0
		lineageTag: 680a726f-7b92-4beb-8f6e-7e6e39740c1e
		summarizeBy: sum
		sourceColumn: gross_profit_budget

		annotation SummarizationSetBy = Automatic

	partition fact_budget = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Projects\cafe-retail-data-generator\fact_budget.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"outlet_id", Int64.Type}, {"year_month_id", Int64.Type}, {"product_id", Int64.Type}, {"cups_sold_budget", Int64.Type}, {"gross_sales_budget", Int64.Type}, {"discount_budget", Int64.Type}, {"net_sales_budget", Int64.Type}, {"cost_budget", Int64.Type}, {"gross_profit_budget", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

